server:
  port: 8011
  
eureka:
  instance: 
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

      
spring:
  application:
    name: employee-service
    
logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG 
      
  